version: "3.3"
# name: "electric_quickstart"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      # Do not expose your Neon credentials to the browser
      PGHOST: ep-black-dew-a91905lp.gwc.azure.neon.tech
      PGDATABASE: neondb
      PGUSER: neondb_owner
      PGPASSWORD: npg_EbFezqc9ZR4v
      # POSTGRES_DB: electric
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_EbFezqc9ZR4v@ep-black-dew-a91905lp.gwc.azure.neon.tech/neondb?sslmode=require
    ports:
      - "3000:3000"
    depends_on:
      - postgres
